version: "3"

services:
  frontend:
    image: ${IMAGE}:latest
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ID=0oa2tf8scutCJanMj696
      - ISSUER=https://nuevesolutions.okta.com/oauth2/default
